project:
  type: website
  output-dir: docs

website:
  title: "NAA-UK Academics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

  margin-header: |
    ![](./naa-uk-academics-logo.png)

format:
  html:
    theme:
      - pulse
    css: styles.css
    toc: true



