project:
  type: website
  output-dir: _site

website:
  title: "NAA-UK Academics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



